# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lakshya Dubey
title: Associate Threat Researcher
email: 0xlakshya.re@gmail.com
website: https://themalhunt.wordpress.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Lakshya and I'm a Associate Threat Researcher and an enduring learner of technology and security enthusiasts. Currently a final year computer science student (Bachelors of Technology), also one of the respected chapter leaders in the Null Open Security community, and OWASP Bhopal, India
  chapter. I can analyze Malware and can write YARA rules for extracting signatures of malware. I've also got the skills of memory forensics.
  I am most skilled in: <mark>Threat Hunting</mark> Darkweb Monitoring <mark>Malware Analysis</mark> Reverse Engineering <mark> Memory Forensics </mark> Yara Rules


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Aghor
        link: github.com/imendax
        # link_text: Project Website
        additional_links:
          - title:  imendax/Aghor
            icon: fab fa-github
            url: github.com/imendax/Aghor
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Signature based malware detection tool.
        description: | # this will include new lines to allow paragraphs
          Aghor is a signature based malware detection tool. Aghor is a signature-based malware detection tool. Which utilizes the capabilities of Yara to identify that the given file is malicious or not.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Confidential
        link: themalhunt.wordpress.com
        # link_text: boringcompany.com
        sub_title: Associate Threat Researcher
        caption: May 2021 - Present
        quote: > #quote
          
        description: | # this will include new lines to allow paragraphs
          My task as a Associate Threat Researcher includes build and maintain targets that allow for the efficient and accurate collection of information of threat intelligence value in order to satisfy research requirements. Monitor specific cyber threat actors or groups to understand their tactics, techniques, and procedures.Monitor specific cyber threat actors or groups to understand their tactics, techniques, and procedures. Tracking cybercrime and hacktivism threats in EMEA based on based on technical analysis, forums and social media monitoring, and publicly available sources.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RGPV University
        caption: 2018 - 2021
        sub_title: Btech Computer Science
        quote: > #quote
                
        description: | # this will include new lines to allow paragraphs
          Mostly I'm self-thought, during my college time I tried to learn various skills including Malware Analysis, Threat Hunting, Darkweb Monitoring, Yara Rules, Memory Forensics, etc. At the same time, I've successfully published two different research papers and presented spoked at national and international conferences. .

          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
